server:
    port: 8080
    servlet:
    context-path: /scpsurf

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_scpsurf?useTimezone=true&serverTimezone=America/Sao_Paulo
        username: root
        password: 78541200
    jpa:
        show-sql: true
        database-plataform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
    hibernate:
        ddl-auto: none
application:
    description: Sistema de certificação de Propiedade de pranchas de surf
    version: 1.2
